name: Deploy Docker Image to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t my-docker-image:latest .
        docker tag my-docker-image:latest <your-dockerhub-username>/my-docker-image:latest
        docker push <your-dockerhub-username>/my-docker-image:latest

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "${EC2_SSH_KEY}" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_INSTANCE_ID} << 'EOF'
          docker pull <your-dockerhub-username>/my-docker-image:latest
          docker stop my-running-container || true
          docker rm my-running-container || true
          docker run -d --name my-running-container <your-dockerhub-username>/my-docker-image:latest
        EOF


     
      
