name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Wait for MySQL to be ready
        run: |
          dockerize -wait tcp://localhost:3306 -timeout 1m
      
      - name: Run MySQL script
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -p$MYSQL_ROOT_PASSWORD testdb < path/to/your/script.sql

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image
        id: build-image
        run: |
          IMAGE_NAME=donsmart/ticketreservation
          TAG_NAME=latest
          
          docker build -t $IMAGE_NAME:$TAG_NAME .
          docker push $IMAGE_NAME:$TAG_NAME
